//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshCentralRouter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeshCentralRouter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} users.
        /// </summary>
        internal static string AddXUsers {
            get {
                return ResourceManager.GetString("AddXUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Displays.
        /// </summary>
        internal static string AllDisplays {
            get {
                return ResourceManager.GetString("AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost done.
        /// </summary>
        internal static string Almostdone {
            get {
                return ResourceManager.GetString("Almostdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMT.
        /// </summary>
        internal static string AMT {
            get {
                return ResourceManager.GetString("AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowleft16 {
            get {
                object obj = ResourceManager.GetObject("arrowleft16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowright16 {
            get {
                object obj = ResourceManager.GetObject("arrowright16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change remote desktop settings.
        /// </summary>
        internal static string ChangeRemoteDesktopSettings {
            get {
                return ResourceManager.GetString("ChangeRemoteDesktopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIRA.
        /// </summary>
        internal static string CIRA {
            get {
                return ResourceManager.GetString("CIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Computer50 {
            get {
                object obj = ResourceManager.GetObject("Computer50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        internal static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete16 {
            get {
                object obj = ResourceManager.GetObject("delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        internal static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display connection statistics.
        /// </summary>
        internal static string DisplayConnectionStatistics {
            get {
                return ResourceManager.GetString("DisplayConnectionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display {0}.
        /// </summary>
        internal static string DisplayX {
            get {
                return ResourceManager.GetString("DisplayX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask for {0} days..
        /// </summary>
        internal static string DontAskXDays {
            get {
                return ResourceManager.GetString("DontAskXDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification required.
        /// </summary>
        internal static string EmailVerificationRequired {
            get {
                return ResourceManager.GetString("EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmptyBanner {
            get {
                object obj = ResourceManager.GetObject("EmptyBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading file: {0}.
        /// </summary>
        internal static string ErrorDownloadingFileX {
            get {
                return ResourceManager.GetString("ErrorDownloadingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading file: {0}.
        /// </summary>
        internal static string ErrorUploadingFileX {
            get {
                return ResourceManager.GetString("ErrorUploadingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating....
        /// </summary>
        internal static string EstimatingDotDotDot {
            get {
                return ResourceManager.GetString("EstimatingDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start remote desktop session.
        /// </summary>
        internal static string FailedToStartRemoteDesktopSession {
            get {
                return ResourceManager.GetString("FailedToStartRemoteDesktopSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start remote terminal session.
        /// </summary>
        internal static string FailedToStartRemoteTerminalSession {
            get {
                return ResourceManager.GetString("FailedToStartRemoteTerminalSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder36 {
            get {
                object obj = ResourceManager.GetObject("Folder36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foldernew16 {
            get {
                object obj = ResourceManager.GetObject("foldernew16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderroot16 {
            get {
                object obj = ResourceManager.GetObject("folderroot16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderup16 {
            get {
                object obj = ResourceManager.GetObject("folderup16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderzip {
            get {
                object obj = ResourceManager.GetObject("folderzip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gear20 {
            get {
                object obj = ResourceManager.GetObject("Gear20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help20 {
            get {
                object obj = ResourceManager.GetObject("Help20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpRelayMap {
            get {
                object obj = ResourceManager.GetObject("HelpRelayMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_monitor1 {
            get {
                object obj = ResourceManager.GetObject("icon-monitor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconClipboardIn {
            get {
                object obj = ResourceManager.GetObject("iconClipboardIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconClipboardOut {
            get {
                object obj = ResourceManager.GetObject("iconClipboardOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons01 {
            get {
                object obj = ResourceManager.GetObject("icons01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Individual Devices).
        /// </summary>
        internal static string IndividualDevices {
            get {
                return ResourceManager.GetString("IndividualDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid download..
        /// </summary>
        internal static string InvalidDownload {
            get {
                return ResourceManager.GetString("InvalidDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing language will close this tool. Are you sure?.
        /// </summary>
        internal static string LanguagesChanging {
            get {
                return ResourceManager.GetString("LanguagesChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguagesTitle {
            get {
                return ResourceManager.GetString("LanguagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local - {0}.
        /// </summary>
        internal static string LocalPlus {
            get {
                return ResourceManager.GetString("LocalPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to host: {0}..
        /// </summary>
        internal static string LockedToHost {
            get {
                return ResourceManager.GetString("LockedToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to server id: {0}..
        /// </summary>
        internal static string LockedToServerId {
            get {
                return ResourceManager.GetString("LockedToServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} connections..
        /// </summary>
        internal static string ManyConnections {
            get {
                return ResourceManager.GetString("ManyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MC2Banner {
            get {
                object obj = ResourceManager.GetObject("MC2Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MeshCentral {
            get {
                object obj = ResourceManager.GetObject("MeshCentral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshCentral Router.
        /// </summary>
        internal static string MeshCentralRouter {
            get {
                return ResourceManager.GetString("MeshCentralRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshCentral.
        /// </summary>
        internal static string MeshCentralTitle {
            get {
                return ResourceManager.GetString("MeshCentralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent.
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT.
        /// </summary>
        internal static string MQTT {
            get {
                return ResourceManager.GetString("MQTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tools allowed.
        /// </summary>
        internal static string NoToolsAllowed {
            get {
                return ResourceManager.GetString("NoToolsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Byte.
        /// </summary>
        internal static string OneByte {
            get {
                return ResourceManager.GetString("OneByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , 1 connection..
        /// </summary>
        internal static string OneConnection {
            get {
                return ResourceManager.GetString("OneConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSSH.
        /// </summary>
        internal static string OpenSSHAppName {
            get {
                return ResourceManager.GetString("OpenSSHAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite 1 file?.
        /// </summary>
        internal static string OverwriteOneFile {
            get {
                return ResourceManager.GetString("OverwriteOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite {0} files?.
        /// </summary>
        internal static string OverwriteXfiles {
            get {
                return ResourceManager.GetString("OverwriteXfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} to {1}:{2}.
        /// </summary>
        internal static string PortXtoIPPortY {
            get {
                return ResourceManager.GetString("PortXtoIPPortY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} to port {1}.
        /// </summary>
        internal static string PortXtoPortY {
            get {
                return ResourceManager.GetString("PortXtoPortY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull clipboard from remote device.
        /// </summary>
        internal static string PullClipboardFromRemoteDevice {
            get {
                return ResourceManager.GetString("PullClipboardFromRemoteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push local clipboard to remote device.
        /// </summary>
        internal static string PushLocaClipboardToRemoteDevice {
            get {
                return ResourceManager.GetString("PushLocaClipboardToRemoteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuTTY SSH client.
        /// </summary>
        internal static string PuttyAppName {
            get {
                return ResourceManager.GetString("PuttyAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid network data.
        /// </summary>
        internal static string ReceivedInvalidNetworkData {
            get {
                return ResourceManager.GetString("ReceivedInvalidNetworkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Recorded Session.
        /// </summary>
        internal static string RecordedSession {
            get {
                return ResourceManager.GetString("RecordedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh16 {
            get {
                object obj = ResourceManager.GetObject("refresh16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay.
        /// </summary>
        internal static string Relay {
            get {
                return ResourceManager.GetString("Relay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        internal static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote - {0}.
        /// </summary>
        internal static string RemotePlus {
            get {
                return ResourceManager.GetString("RemotePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 1 item?.
        /// </summary>
        internal static string Remove1Item {
            get {
                return ResourceManager.GetString("Remove1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} items?.
        /// </summary>
        internal static string RemoveXItems {
            get {
                return ResourceManager.GetString("RemoveXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ctrl-Alt-Del to remote device.
        /// </summary>
        internal static string SendCtrlAltDelToRemoteDevice {
            get {
                return ResourceManager.GetString("SendCtrlAltDelToRemoteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send token to registered email address?.
        /// </summary>
        internal static string SendTokenEmail {
            get {
                return ResourceManager.GetString("SendTokenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send token to registered messaging application?.
        /// </summary>
        internal static string SendTokenMSG {
            get {
                return ResourceManager.GetString("SendTokenMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send token to registered phone number?.
        /// </summary>
        internal static string SendTokenSMS {
            get {
                return ResourceManager.GetString("SendTokenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup....
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This executable is locked to only connect to {0}..
        /// </summary>
        internal static string SignedExecutableServerLockError {
            get {
                return ResourceManager.GetString("SignedExecutableServerLockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS sent.
        /// </summary>
        internal static string SmsSent {
            get {
                return ResourceManager.GetString("SmsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped2 {
            get {
                return ResourceManager.GetString("Stopped2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle remote desktop connection.
        /// </summary>
        internal static string ToggleRemoteDesktopConnection {
            get {
                return ResourceManager.GetString("ToggleRemoteDesktopConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle zoom-to-fit mode.
        /// </summary>
        internal static string ToggleZoomToFitMode {
            get {
                return ResourceManager.GetString("ToggleZoomToFitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication.
        /// </summary>
        internal static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete 2FA setup online first.
        /// </summary>
        internal static string TwoFactorSetupRequired {
            get {
                return ResourceManager.GetString("TwoFactorSetupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind to local port.
        /// </summary>
        internal static string UnableToBindToLocalPort {
            get {
                return ResourceManager.GetString("UnableToBindToLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file: {0}.
        /// </summary>
        internal static string UnableToOpenFileX {
            get {
                return ResourceManager.GetString("UnableToOpenFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write file: {0}.
        /// </summary>
        internal static string UnableToWriteFileX {
            get {
                return ResourceManager.GetString("UnableToWriteFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very slow.
        /// </summary>
        internal static string VerySlow {
            get {
                return ResourceManager.GetString("VerySlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for user to grant access....
        /// </summary>
        internal static string WaitingForUserToGrantAccess {
            get {
                return ResourceManager.GetString("WaitingForUserToGrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinSCP client.
        /// </summary>
        internal static string WinscpAppName {
            get {
                return ResourceManager.GetString("WinscpAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes.
        /// </summary>
        internal static string XBytes {
            get {
                return ResourceManager.GetString("XBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes/sec.
        /// </summary>
        internal static string XbytesPersec {
            get {
                return ResourceManager.GetString("XbytesPersec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Gbytes/sec.
        /// </summary>
        internal static string XGbytesPersec {
            get {
                return ResourceManager.GetString("XGbytesPersec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours left.
        /// </summary>
        internal static string xhoursleft {
            get {
                return ResourceManager.GetString("xhoursleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xinstall {
            get {
                object obj = ResourceManager.GetObject("xinstall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kbytes/sec.
        /// </summary>
        internal static string XKbytesPersec {
            get {
                return ResourceManager.GetString("XKbytesPersec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mbytes/sec.
        /// </summary>
        internal static string XMbytesPersec {
            get {
                return ResourceManager.GetString("XMbytesPersec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes left.
        /// </summary>
        internal static string xminutesleft {
            get {
                return ResourceManager.GetString("xminutesleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds left.
        /// </summary>
        internal static string xsecondsleft {
            get {
                return ResourceManager.GetString("xsecondsleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Selected Files.
        /// </summary>
        internal static string ZipSelectedFiles {
            get {
                return ResourceManager.GetString("ZipSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomToFit {
            get {
                object obj = ResourceManager.GetObject("ZoomToFit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
