//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeshCentralRouter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeshCentralRouter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50_Computer {
            get {
                object obj = ResourceManager.GetObject("50-Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMT.
        /// </summary>
        internal static string AMT {
            get {
                return ResourceManager.GetString("AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIRA.
        /// </summary>
        internal static string CIRA {
            get {
                return ResourceManager.GetString("CIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification required.
        /// </summary>
        internal static string EmailVerificationRequired {
            get {
                return ResourceManager.GetString("EmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmptyBanner {
            get {
                object obj = ResourceManager.GetObject("EmptyBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder36 {
            get {
                object obj = ResourceManager.GetObject("Folder36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gear20 {
            get {
                object obj = ResourceManager.GetObject("Gear20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help20 {
            get {
                object obj = ResourceManager.GetObject("Help20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpRelayMap {
            get {
                object obj = ResourceManager.GetObject("HelpRelayMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons01 {
            get {
                object obj = ResourceManager.GetObject("icons01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing language will close this tool. Are you sure?.
        /// </summary>
        internal static string LanguagesChanging {
            get {
                return ResourceManager.GetString("LanguagesChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguagesTitle {
            get {
                return ResourceManager.GetString("LanguagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} connections..
        /// </summary>
        internal static string ManyConnections {
            get {
                return ResourceManager.GetString("ManyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MC2Banner {
            get {
                object obj = ResourceManager.GetObject("MC2Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MeshCentral {
            get {
                object obj = ResourceManager.GetObject("MeshCentral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshCentral Router.
        /// </summary>
        internal static string MeshCentralRouter {
            get {
                return ResourceManager.GetString("MeshCentralRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshCentral.
        /// </summary>
        internal static string MeshCentralTitle {
            get {
                return ResourceManager.GetString("MeshCentralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT.
        /// </summary>
        internal static string MQTT {
            get {
                return ResourceManager.GetString("MQTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , 1 connection..
        /// </summary>
        internal static string OneConnection {
            get {
                return ResourceManager.GetString("OneConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuTTY SSH client.
        /// </summary>
        internal static string PuttyAppName {
            get {
                return ResourceManager.GetString("PuttyAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay.
        /// </summary>
        internal static string Relay {
            get {
                return ResourceManager.GetString("Relay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send token to registered email address?.
        /// </summary>
        internal static string SendTokenEmail {
            get {
                return ResourceManager.GetString("SendTokenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send token to registered phone number?.
        /// </summary>
        internal static string SendTokenSMS {
            get {
                return ResourceManager.GetString("SendTokenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS sent.
        /// </summary>
        internal static string SmsSent {
            get {
                return ResourceManager.GetString("SmsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped2 {
            get {
                return ResourceManager.GetString("Stopped2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor Authentication.
        /// </summary>
        internal static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind to local port.
        /// </summary>
        internal static string UnableToBindToLocalPort {
            get {
                return ResourceManager.GetString("UnableToBindToLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinSCP client.
        /// </summary>
        internal static string WinscpAppName {
            get {
                return ResourceManager.GetString("WinscpAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xinstall {
            get {
                object obj = ResourceManager.GetObject("xinstall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
